services:
  cdn_app:
    build:
      context: .
    container_name: cdn_app
    restart: unless-stopped
    volumes:
      - ./storage:/app/storage
    env_file: .env
    networks:
      - web-gateway

networks:
  web-gateway:
    external: true
